const path = require('path')
const fsPromises = require('fs').promises

const fileOps = async () =>{
    try{
        const data = await fsPromises.readFile(path.join(__dirname,'Files','start.txt'),'utf8')
        console.log(data)
        await fsPromises.writeFile(path.join(__dirname,'Files','js.txt'),'Shiva Safana')
            console.log('Write complete')
        await fsPromises.appendFile(path.join(__dirname,'Files','js.txt'),'VVV')
            console.log('append complete')
        await fsPromises.rename(path.join(__dirname,'Files','js.txt'),path.join(__dirname,'Files','ssvvv.txt'))
            console.log('Rename complete')
        
        await fsPromises.unlink(path.join(__dirname,'Files','ks.txt'))
        
    }catch(err){
        console.error(err)
    }
}
fileOps()

//exit on uncaught errors
process.on('uncaughtException',err => {
    console.error(`There was an uncaught error: ${err}`)
    process.exit(1)
})